version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["yarn", "start"]
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
  prod:
    build: .
    ports:
      - "80:80"
